"""
CrackTheDeck — Email report delivery via Resend.

Sends the generated PDF report to the user's email address.

Usage in main.py:
    from resend_emails import router as email_router
    app.include_router(email_router)

Env vars required:
    RESEND_API_KEY — re_... API key from Resend dashboard
"""

import os
import logging
import base64
from pathlib import Path
from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel, EmailStr

logger = logging.getLogger("resend_emails")

router = APIRouter(prefix="/api/email", tags=["email"])

# ---------------------------------------------------------------------------
# Resend SDK init
# ---------------------------------------------------------------------------
try:
    import resend
except ImportError:
    raise ImportError("resend package not installed. Run: pip install resend")

resend.api_key = os.getenv("RESEND_API_KEY", "")

FROM_EMAIL = os.getenv("RESEND_FROM_EMAIL", "noreply@crackthedeck.com")

# Reports dir — same as config.REPORTS_DIR
_BASE_DIR = Path(__file__).parent
REPORTS_DIR = (_BASE_DIR / "reports").resolve()

# ---------------------------------------------------------------------------
# Request model
# ---------------------------------------------------------------------------

class SendReportRequest(BaseModel):
    email: EmailStr
    report_id: str
    report_type: str = "investor"
    company_name: str = "your deck"

class ContactFormRequest(BaseModel):
    name: str
    email: EmailStr
    message: str

# ---------------------------------------------------------------------------
# Send report endpoint
# ---------------------------------------------------------------------------

@router.post("/send-report")
async def send_report(body: SendReportRequest):
    """
    Send the generated PDF report to the specified email address.
    The PDF must already exist in the reports directory.
    """
    if not resend.api_key:
        logger.error("RESEND_API_KEY not set")
        raise HTTPException(500, "Email service not configured")

    if body.report_type not in ("investor", "startup"):
        raise HTTPException(400, "report_type must be 'investor' or 'startup'")

    # Find the PDF file
    pdf_path = REPORTS_DIR / f"{body.report_id}_{body.report_type}.pdf"
    if not pdf_path.exists():
        raise HTTPException(404, "Report not found. Please generate the report first.")

    pdf_bytes = pdf_path.read_bytes()
    pdf_b64 = base64.b64encode(pdf_bytes).decode()

    # Build a clean filename for the attachment
    safe_company = "".join(c for c in body.company_name if c.isalnum() or c in " _-").strip()
    if not safe_company:
        safe_company = "Report"
    attachment_name = f"CrackTheDeck_{safe_company}_{body.report_type}.pdf"

    # Compose email
    report_label = "Investor Report" if body.report_type == "investor" else "Startup Report"

    html_body = f"""
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px 24px;">
        <div style="text-align: center; margin-bottom: 32px;">
            <h1 style="font-size: 24px; font-weight: 700; color: #111; margin: 0;">
                &#9889; CrackTheDeck
            </h1>
        </div>
        <div style="background: #f9fafb; border-radius: 12px; padding: 24px; margin-bottom: 24px;">
            <h2 style="font-size: 18px; font-weight: 600; color: #111; margin: 0 0 8px 0;">
                Your {report_label} is ready
            </h2>
            <p style="color: #555; font-size: 14px; line-height: 1.6; margin: 0;">
                We've analyzed <strong>{body.company_name}</strong> and attached the full PDF report to this email.
            </p>
        </div>
        <p style="color: #888; font-size: 12px; text-align: center; margin-top: 32px;">
            This report was generated by <a href="https://crackthedeck.com" style="color: #6366f1; text-decoration: none;">CrackTheDeck</a> — AI-powered pitch deck analysis.
        </p>
    </div>
    """

    try:
        params = {
            "from": FROM_EMAIL,
            "to": [body.email],
            "subject": f"CrackTheDeck — {report_label} for {body.company_name}",
            "html": html_body,
            "attachments": [
                {
                    "filename": attachment_name,
                    "content": pdf_b64,
                    "content_type": "application/pdf",
                }
            ],
        }
        result = resend.Emails.send(params)
        logger.info(f"Email sent to {body.email}, resend_id={result.get('id', 'unknown')}")
        return JSONResponse({
            "success": True,
            "message": f"Report sent to {body.email}",
            "resend_id": result.get("id"),
        })

    except Exception as e:
        logger.error(f"Failed to send email to {body.email}: {e}")
        raise HTTPException(502, f"Failed to send email: {str(e)}")


# ---------------------------------------------------------------------------
# Report pending review notification (Pro/Expert plans)
# ---------------------------------------------------------------------------

class ReportPendingRequest(BaseModel):
    email: EmailStr
    company_name: str = "your deck"
    plan: str = "pro"

@router.post("/report-pending")
async def report_pending(body: ReportPendingRequest):
    """Send a notification that the report is being reviewed by the team."""
    if not resend.api_key:
        logger.error("RESEND_API_KEY not set")
        raise HTTPException(500, "Email service not configured")

    plan_label = "Expert" if body.plan == "expert" else "Pro"

    html_body = f"""
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px 24px;">
        <div style="text-align: center; margin-bottom: 32px;">
            <h1 style="font-size: 24px; font-weight: 700; color: #111; margin: 0;">
                &#9889; CrackTheDeck
            </h1>
        </div>
        <div style="background: #f9fafb; border-radius: 12px; padding: 24px; margin-bottom: 24px;">
            <h2 style="font-size: 18px; font-weight: 600; color: #111; margin: 0 0 12px 0;">
                Your {plan_label} Review is in progress
            </h2>
            <p style="color: #555; font-size: 14px; line-height: 1.7; margin: 0 0 12px 0;">
                We've received your pitch deck for <strong>{body.company_name}</strong> and our AI has completed the initial analysis.
            </p>
            <p style="color: #555; font-size: 14px; line-height: 1.7; margin: 0 0 12px 0;">
                Our expert investor team is now reviewing the results and adding personalized feedback based on their experience evaluating hundreds of startups.
            </p>
            <div style="background: #fff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; text-align: center;">
                <p style="font-size: 15px; font-weight: 600; color: #111; margin: 0;">
                    &#128337; Estimated delivery: within 24 hours
                </p>
                <p style="font-size: 13px; color: #888; margin: 4px 0 0;">
                    You'll receive the full PDF report at this email address.
                </p>
            </div>
        </div>
        <p style="color: #888; font-size: 12px; text-align: center; margin-top: 32px;">
            This is an automated confirmation from <a href="https://crackthedeck.com" style="color: #6366f1; text-decoration: none;">CrackTheDeck</a>.
        </p>
    </div>
    """

    try:
        params = {
            "from": FROM_EMAIL,
            "to": [body.email],
            "subject": f"CrackTheDeck — Your {plan_label} Review is in progress",
            "html": html_body,
        }
        result = resend.Emails.send(params)
        logger.info(f"Pending-review email sent to {body.email}, resend_id={result.get('id', 'unknown')}")
        return JSONResponse({"success": True, "message": f"Notification sent to {body.email}"})

    except Exception as e:
        logger.error(f"Failed to send pending-review email to {body.email}: {e}")
        raise HTTPException(502, f"Failed to send email: {str(e)}")


# ---------------------------------------------------------------------------
# Contact form endpoint
# ---------------------------------------------------------------------------

SUPPORT_EMAIL = os.getenv("SUPPORT_EMAIL", "alekseyposternak@gmail.com")

def _log_contact_db(name, email, message):
    try:
        from admin_db import log_contact
        log_contact(name=name, email=email, message=message)
    except Exception:
        pass

@router.post("/contact")
async def contact_form(body: ContactFormRequest):
    """
    Receive a support/contact message and forward it to the team email.
    """
    if not resend.api_key:
        logger.error("RESEND_API_KEY not set")
        raise HTTPException(500, "Email service not configured")

    if not body.name.strip() or not body.message.strip():
        raise HTTPException(400, "Name and message are required")

    # Limit message length
    msg_text = body.message.strip()[:5000]
    sender_name = body.name.strip()[:200]

    html_body = f"""
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px 24px;">
        <h2 style="font-size: 20px; font-weight: 600; color: #111; margin: 0 0 16px;">New Support Message</h2>
        <div style="background: #f9fafb; border-radius: 12px; padding: 20px; margin-bottom: 16px;">
            <p style="margin: 0 0 8px; font-size: 14px;"><strong>From:</strong> {sender_name} &lt;{body.email}&gt;</p>
            <p style="margin: 0; font-size: 14px; white-space: pre-wrap; line-height: 1.6;">{msg_text}</p>
        </div>
        <p style="color: #888; font-size: 12px;">Sent via CrackTheDeck contact form</p>
    </div>
    """

    try:
        params = {
            "from": FROM_EMAIL,
            "to": [SUPPORT_EMAIL],
            "reply_to": body.email,
            "subject": f"[CrackTheDeck Support] Message from {sender_name}",
            "html": html_body,
        }
        result = resend.Emails.send(params)
        logger.info(f"Contact form from {body.email}, resend_id={result.get('id', 'unknown')}")
        _log_contact_db(sender_name, body.email, msg_text)
        return JSONResponse({
            "success": True,
            "message": "Message sent successfully",
        })

    except Exception as e:
        logger.error(f"Failed to send contact form from {body.email}: {e}")
        raise HTTPException(502, f"Failed to send message: {str(e)}")
